language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - nightly

notifications:
  email: false

git:
  depth: 99999999

matrix:
 allow_failures:
 - julia: nightly

script:
 - julia --project=docs/ docs/make.jl
