language: julia

os:
  - linux

julia:
  - 1.0.3

script:
  - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
  - julia --project=docs/ docs/make.jl deploy
